# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname ="centos7-vm"

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = config.vm.hostname

    v.memory = 4096
    v.cpus = 4

    v.customize ["modifyvm", :id, "--audio", "none"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    v.customize ["modifyvm", :id, "--spec-ctrl", "on"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "shell", path: "./setup.sh", privileged: false

end
