---
- hosts: all
  name: Set up VM for Ansible role development

  roles:
    - role: geerlingguy.repo-epel
      become: true
      
    - role: sthdev.update_packages
      become: true

    - role: sthdev.install_gnome
      become: true

    - role: geerlingguy.pip
      pip_install_packages:
        - docker
      become: true
    
    - role: geerlingguy.docker
      docker_compose_version: "1.25.3"
      docker_compose_path: /usr/bin/docker-compose
      docker_users:
        - vagrant
      become: true

    - role: gantsign.visual-studio-code
      users:
        - username: vagrant
          visual_studio_code_extensions:
            - eamodio.gitlens
            - ms-azuretools.vscode-docker
            - ms-python.python
            - vscoss.vscode-ansible


