---
- hosts: all
  name: Set up VM for Ansible role development

  roles:
    - { role: geerlingguy.repo-epel, become: true }
    - { role: sthdev.update_packages, become: true }
    - { role: sthdev.install_gnome, become: true}