---
- src: gantsign.visual-studio-code
  version: 6.4.0
- src: geerlingguy.docker
  version: 2.6.0
- src: geerlingguy.pip
  version: 1.3.0
- src: geerlingguy.repo-epel
  version: 1.2.4
- src: sthdev.update_packages
  version: v1.0.0
- src: sthdev.install_gnome
  version: 1.0.0