# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname ="ansible-role-dev"

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.name = config.vm.hostname

    v.memory = 4096
    v.cpus = 4

    v.customize ["modifyvm", :id, "--audio", "none"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    v.customize ["modifyvm", :id, "--spec-ctrl", "on"]
    v.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "file", source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"

  config.vm.provision "shell", inline: <<-SCRIPT
    chown vagrant:vagrant /home/vagrant/.gitconfig
    chown vagrant:vagrant /home/vagrant/.ssh/id_rsa
    chown vagrant:vagrant /home/vagrant/.ssh/id_rsa.pub

    chmod 600 /home/vagrant/.ssh/id_rsa.pub
  SCRIPT

  config.vm.provision "ansible_local" do |ansible|
    ansible.galaxy_role_file = "requirements.yml"
    ansible.playbook = "playbook.yml"
  end
  

end
